##
##  HUDS -- Head-Up-Display Server (HUDS)
##  Copyright (c) 2020-2023 Dr. Ralf S. Engelschall <rse@engelschall.com>
##
##  Permission is hereby granted, free of charge, to any person obtaining
##  a copy of this software and associated documentation files (the
##  "Software"), to deal in the Software without restriction, including
##  without limitation the rights to use, copy, modify, merge, publish,
##  distribute, sublicense, and/or sell copies of the Software, and to
##  permit persons to whom the Software is furnished to do so, subject to
##  the following conditions:
##
##  The above copyright notice and this permission notice shall be included
##  in all copies or substantial portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
##  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
##  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
##  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
##  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
##  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
##  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

id:
    peer:                  "training-peer"

title:
    opacity:               0.80
    background:            "#336699"
    iconname:              graduation-cap
    iconcolor:             "#77aadd"
    nametext:              John Doe
    namecolor:             "#e0f0ff"
    titletext:             LiVE Sample Session
    titlecolor:            "#ffffff"

attendance:
    opacity:               0.80
    background:            "#336699"
    iconcolor:             "#77aadd"
    textcolor:             "#e0f0ff"

attendees:
    opacity:               0.80
    background:            "#336699"
    namecolorbg:           "#003366"
    namecolorfg:           "#e0f0ff"
    noattendeestext:       "This training has still no identified attendees."
    privacylevel:          closed

feedback:
    opacity:               0.80
    surprisecolor1:        "#222222"
    surprisecolor2:        "#f0f0f0"
    surprisecolor3:        "#c0c0c0"
    surprisecolor4:        "#000000"
    smilecolor1:           "#221100"
    smilecolor2:           "#d08840"
    smilecolor3:           "#a05810"
    smilecolor4:           "#ffffff"
    frowncolor1:           "#99ccff"
    frowncolor2:           "#336699"
    frowncolor3:           "#003366"
    frowncolor4:           "#ffffff"
    sadnesscolor1:         "#cccccc"
    sadnesscolor2:         "#333333"
    sadnesscolor3:         "#000000"
    sadnesscolor4:         "#ffffff"
    thumbsupcolor1:        "#336699"
    thumbsupcolor2:        "#e0f0ff"
    thumbsupcolor3:        "#003366"
    thumbsupcolor4:        "#ffffff"
    thumbsdncolor1:        "#904800"
    thumbsdncolor2:        "#ffb870"
    thumbsdncolor3:        "#702200"
    thumbsdncolor4:        "#ffffff"

feeling:
    opacity:               0.80
    background:            "#336699"
    textcolor:             "#e0f0ff"
    stdbarcolor:           "#d0e0f0"
    maxbarcolor:           "#ffffff"
    bordercolor:           "#99ccff"
    legendcolor:           "#ffffff"
    c1color:               "#b06820"
    c2color:               "#909090"
    c3color:               "#336699"
    c4color:               "#909090"
    c5color:               "#b06820"
    m1color:               "#905810"
    m2color:               "#b06820"
    m3color:               "#909090"
    m4color:               "#336699"
    m5color:               "#225588"

closure:
    opacity:               0.75
    background1:           "#000000"
    background2:           "#222222"
    beginiconname:         "play-circle"
    beginiconcolor:        "#b06820"
    beginhinttext:         "The training will start soon.<br/>Please be patient!"
    beginhintcolor:        "#ffffff"
    pauseiconname:         "pause-circle"
    pauseiconcolor:        "#336699"
    pausehinttext:         "The training is paused.<br/>Please be patient!"
    pausehintcolor:        "#ffffff"
    endiconname:           "stop-circle"
    endiconcolor:          "#b06820"
    endhinttext:           "The training already has ended.<br/>Thanks for your attention!"
    endhintcolor:          "#ffffff"
    privacylevel:          closed
    privacyclosedtext:     "Notice: this training is broadcasted in <b>private</b> to a <b>closed</b> group. Identities of attendees with just <b>anonymous</b> privacy level will not be disclosed, of course. Set your privacy level in your <b><i>LiVE Receiver</i></b> to at least <b>private</b> or even <b>public</b> to have your identity be disclosed, please."
    privacyopentext:       "Notice: this training is broadcasted in <b>public</b> to an <b>open</b> group. Identities of attendees with just <b>anonymous</b> or <b>private</b> privacy level will not be disclosed, of course. Set your privacy level in your <b><i>LiVE Receiver</i></b> to <b>public</b> to have your identity be disclosed, please."

popup:
    opacity:               0.80
    questionbackground:    "#336699"
    questiontitlecolor:    "#e0f0ff"
    questionmessagecolor:  "#ffffff"
    objectionbackground:   "#333333"
    objectiontitlecolor:   "#e0e0e0"
    objectionmessagecolor: "#ffffff"
    commentbackground:     "#f0f0f0"
    commenttitlecolor:     "#333333"
    commentmessagecolor:   "#000000"
    privacylevel:          closed

timer:
    opacity:               0.80
    background1:           "#555555"
    background2:           "#f0f0f0"
    ticks:                 "#333333"
    digits:                "#666666"
    pointer1:              "#000000"
    pointer2:              "#222222"
    pointer3:              "#cc3333"
    segment1:              "#b06820"
    segment2:              "#f4dbc2"
    segment3:              "#2068b0"
    segment4:              "#c2dbf4"

progress:
    opacity:               0.80
    donecolorbg:           "#6699cc"
    donecolorfg:           "#f0f0ff"
    currcolorbg:           "#336699"
    currcolorfg:           "#ffffff"
    todocolorbg:           "#f0f0f0"
    todocolorfg:           "#999999"

votes:
    opacity:               0.90
    winnamecolorbg:        "#b06820"
    winnamecolorfg:        "#ffffff"
    maxnamecolorbg:        "#336699"
    maxnamecolorfg:        "#ffffff"
    stdnamecolorbg:        "#6699cc"
    stdnamecolorfg:        "#ffffff"
    xtrnamecolorbg:        "#999999"
    xtrnamecolorfg:        "#ffffff"
    winvotecolorbg:        "#ffffff"
    winvotecolorfg:        "#666666"
    maxvotecolorbg:        "#ffffff"
    maxvotecolorfg:        "#666666"
    stdvotecolorbg:        "#f0f0f0"
    stdvotecolorfg:        "#999999"
    xtrvotecolorbg:        "#f0f0f0"
    xtrvotecolorfg:        "#999999"
    allvotecolorbg:        "#60606080"
    allvotecolorbd:        "#999999"
    quizidcolorbg:         "#225588"
    quizidcolorfg:         "#e0e0ff"
    quiztxtcolorbg:        "#336699"
    quiztxtcolorfg:        "#ffffff"
    hintcolorbg:           "#f0f0f0"
    hintcolorfg:           "#666666"
    hintjudge:             "Please <i>judge</i> with a <i>boolean</i> vote now<br/>by selecting one of the choices <kbd>Yes</kbd> or <kbd>No</kbd>!"
    hintevaluate:          "Please <i>evaluate</i> with a <i>positional</i> vote now<br/>by selecting one of the choices <kbd>-2</kbd>, <kbd>-1</kbd>, <kbd>0</kbd>, <kbd>+1</kbd>, <kbd>+2</kbd>!"
    hintquiz:              "Please <i>choose</i> with a <i>numeric</i> vote now<br/>by selecting one of the choices <kbd>1</kbd>, <kbd>2</kbd>, ..."
    hintchoose:            "Please <i>choose</i> with a <i>numeric</i> vote now<br/>by selecting one of the choices <kbd>1</kbd>, <kbd>2</kbd>, ..., <kbd>9</kbd>!"
    hintpropose:           "Please <i>propose</i> with a <i>textual</i> vote now<br/>by sending your proposal as a single word <kbd>XYZ...</kbd>!"
    quizzes:
        -   id:            "01.1-01"
            question:      "What Unix command lists all entries of a directory on the filesystem?"
            right:         "ls"
            wrong:
                -          "dir"
                -          "cd"
                -          "sed"
                -          "awk"
                -          "ed"
        -   id:            "01.1-02"
            question:      "What Unix command can change the lines of a text file through complex calculating expressions?"
            right:         "awk"
            wrong:
                -          "ed"
                -          "sed"
                -          "expr"
                -          "calc"

banner:
    opacity:               0.80
    background:            "#f0f0f0"
    banner:
        -   name:          pause
            key:           p
            iconname:      pause-circle
            iconcolor:     "#336699"
            titletext:     PAUSE
            titlecolor:    "#000000"
        -   name:          rant
            key:           r
            iconname:      radiation-alt
            iconcolor:     "#bb0000"
            titletext:     RANT
            titlecolor:    "#000000"
        -   name:          praise
            key:           x
            iconname:      award
            iconcolor:     "#336699"
            titletext:     PRAISE
            titlecolor:    "#000000"
        -   name:          qna
            key:           q
            iconname:      comments
            iconcolor:     "#b06820"
            titletext:     "Q&A"
            titlecolor:    "#000000"

logo:
    opacity:               0.60
    svg: |
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 109.82 54.29">
          <defs>
            <style>.cls-1{fill:#fff;}.cls-2{fill:#ddd;}</style>
          </defs>
          <path class="cls-1" d="M50.66,50.4l-.77,3.16c-2.32.92-4.17,1.61-5.56,2.09a14.65,14.65,0,0,1-4.81.73A9.61,9.61,0,0,1,33,54.32a6.64,6.64,0,0,1-2.34-5.22,18.23,18.23,0,0,1,.18-2.52,28,28,0,0,1,.56-2.9l2.9-10.26c.26-1,.48-1.92.66-2.8a12.79,12.79,0,0,0,.26-2.4,3.73,3.73,0,0,0-.81-2.75,4.62,4.62,0,0,0-3.1-.77,8.15,8.15,0,0,0-2.31.35c-.79.24-1.47.46-2,.67l.77-3.16c1.91-.78,3.72-1.44,5.46-2a16.38,16.38,0,0,1,4.93-.83,9.45,9.45,0,0,1,6.46,2A6.73,6.73,0,0,1,46.82,27c0,.45-.06,1.23-.16,2.36a16.47,16.47,0,0,1-.58,3.09L43.19,42.7a27.67,27.67,0,0,0-.64,2.81,14.66,14.66,0,0,0-.28,2.39,3.43,3.43,0,0,0,.91,2.78,5.14,5.14,0,0,0,3.16.74,8.94,8.94,0,0,0,2.39-.37A13.47,13.47,0,0,0,50.66,50.4Z" transform="translate(-3.57 -2.45)"/>
          <path class="cls-1" d="M50.66,11.79a6,6,0,0,1-2,4.55,7.27,7.27,0,0,1-9.76,0,6.12,6.12,0,0,1,0-9.12,7.22,7.22,0,0,1,9.76,0A6,6,0,0,1,50.66,11.79Z" transform="translate(-3.57 -2.45)"/>
          <path class="cls-2" d="M81.11,2.45,69,28.05c-2.64,5.6-5.2,11.36-7.2,16.65h-.16c-.32-5.6-.72-10.81-1.28-16.57L58,2.45H46.07l.19,1.48A8.65,8.65,0,0,1,49.94,6a7.67,7.67,0,0,1,2.56,5.78,7.62,7.62,0,0,1-2.56,5.77,9.4,9.4,0,0,1-1.82,1.31l4.67,37.51H66.15L94,2.45Z" transform="translate(-3.57 -2.45)"/>
          <path class="cls-2" d="M30.72,55.12a7,7,0,0,1-2.45-5.48A19.71,19.71,0,0,1,28.45,47l.06-.34H17L25.33,2.83H13.81L3.57,56.75H33.69A7.93,7.93,0,0,1,30.72,55.12Z" transform="translate(-3.57 -2.45)"/>
          <polygon class="cls-2" points="87.34 11.09 69.08 46.45 67.66 53.92 100.78 53.92 102.62 44.08 81.1 44.08 83.58 31.04 102.7 31.04 104.62 21.36 85.34 21.36 87.34 11.09"/>
          <polygon class="cls-2" points="80.18 0 77.9 0 76.36 8.1 80.18 0"/>
          <polygon class="cls-2" points="93.06 0 87.98 9.84 107.9 9.84 109.82 0 93.06 0"/>
        </svg>

latency:
    opacity:               0.80
    background:            "#336699"
    foreground:            "#ffffff"
    iconcolor:             "#77aadd"

confetti:
    opacity:               1.00

snowfall:
    opacity:               0.90

agenda:
    opacity:               0.90
    donecolorbg:           "#6699cc"
    donecolorfg:           "#f0f0ff"
    currcolorbg:           "#336699"
    currcolorfg:           "#ffffff"
    todocolorbg:           "#f0f0f0"
    todocolorfg:           "#999999"
    slots:
        -   Lorem Ipsum 1
        -   Lorem Ipsum 2
        -   Lorem Ipsum 3
        -   Lorem Ipsum 4
        -   BREAK
        -   Lorem Ipsum 5
        -   Lorem Ipsum 6
        -   Lorem Ipsum 7
        -   LUNCH
        -   Lorem Ipsum 8
        -   Lorem Ipsum 9
        -   Lorem Ipsum 10
        -   Lorem Ipsum 11
        -   BREAK
        -   Lorem Ipsum 12
        -   Lorem Ipsum 13
        -   Lorem Ipsum 1
        -   Lorem Ipsum 2
        -   Lorem Ipsum 3
        -   Lorem Ipsum 4

